version: "3.3"

networks:
  default:

services:
  app:
    build:
      context: .
    image: devops-test
    container_name: devops-test
    environment:
      - REDIS_ADDR=redis://localhost:6379
    ports:
      - 8080:8080
      - 9100:9100
    networks:
      - default
    depends_on:
      - redis

  redis:
    image: redis:alpine3.19
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  prometheus:
    image: prom/prometheus:v2.51.0
    volumes:
      - ./prometheus/prom.yml:/etc/prometheus/prometheus.yml
      - prom:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.1.9
    volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/ds.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  redis:
    driver: local
  prom:
    driver: local
