{{ if eq (.Values.deployment.serviceAccount.create | toString) "true" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.deployment.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
  {{- with .Values.deployment.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
{{ end }}
