---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  {{- with .Values.deployment.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      name: {{ .Chart.Name }}
      {{- with .Values.deployment.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      {{- if eq (.Values.deployment.serviceAccount.automount.opt_out | toString) "true" }}
      automountServiceAccountToken: {{ .Values.deployment.serviceAccount.automount.automountServiceAccountToken }}
      {{- end }}
      serviceAccountName: {{ .Values.deployment.serviceAccount.name | default "default" }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}/{{ .Values.image.path }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        command: ["./application"]
        workingDir: /app
        {{- if eq (.Values.livenessProbe.enabled | toString) "true" }}
{{- include "liveness_probe" . | indent 8 }}
        {{- end }}
        {{- if eq (.Values.readinessProbe.enabled | toString) "true" }}
{{- include "readiness_probe" . | indent 8 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.ports.http }}
          name: http
        {{- with .Values.securityContext }}
        securityContext:
{{ toYaml . | indent 10 }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
{{ toYaml . | indent 10 }}
{{- end }}
        env:
        {{- include "common_envs" . | nindent 10 }}
        {{- if .Values.extraEnvs }}
          {{ toYaml .Values.extraEnvs | nindent 10 }}
        {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
      {{- end }}
