{{- if eq (.Values.podMonitor.enabled | toString) "true" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
  {{- with .Values.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  podMetricsEndpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.podMonitor.interval | default "15s" }}
    scrapeTimeout: {{ .Values.podMonitor.scrapeTimeout | default "10s" }}
  {{- with .Values.podMonitor.relabelings }}
    relabelings:
      {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.podMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 4 }}
  {{- end }}
  jobLabel: {{ .Chart.Name }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}
