scrape_configs:
- job_name: application
  scrape_interval: 10s
  static_configs:
  - targets:
    - app:9100
- job_name: redis
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 'redis:9121'
